# Introdução ao `numpy`

In [ ]:
import numpy as np
import matplotlib.pyplot as plt  # Biblioteca para gerar gráficos
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Vamos criar umas matrizes e vetores para começar...

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\ &
\boldsymbol{B} &= \begin{bmatrix}1 & 3\\ 5 & 7\end{bmatrix}\\\\
\boldsymbol{v}_1 &= \begin{bmatrix}5 & 3\end{bmatrix}\ &
\boldsymbol{v}_2 &= \begin{bmatrix}9 & 2 & 1\end{bmatrix}
\end{aligned}$$

In [ ]:
A = np.array([[2,0],[4,6],[8,2]])
B = np.array([[1,3],[5,7]])
v1 = np.array([5,3])
v2 = np.array([9,2,1])

In [ ]:
print("Dimensão de A:", A.shape)
print("Dimensão de B:", B.shape)
print("Dimensão de v1:", v1.shape)
print("Dimensão de v2:", v1.shape)

Dimensão de A: (3, 2)
Dimensão de B: (2, 2)
Dimensão de v1: (2,)
Dimensão de v2: (2,)


$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\boldsymbol{A}^{\top} &= \begin{bmatrix}2 & 4 & 8\\ 0 & 6 & 2\end{bmatrix}
\end{aligned}$$

In [ ]:
print("Matriz original:")
print(A)
print("Matriz transposta:")
print(A.T)

Matriz original:
[[2 0]
 [4 6]
 [8 2]]
Matriz transposta:
[[2 4 8]
 [0 6 2]]


$$\begin{aligned}
\boldsymbol{A}[0] &= \begin{bmatrix}2 & 0\end{bmatrix}\\
\boldsymbol{A}[[0,2]] &= \begin{bmatrix}2 & 0\\ 8 & 2\end{bmatrix}\\
\end{aligned}$$

In [ ]:
print("Primeira linha de A:")
print(A[0], "dimensão:", A[0].shape) # Primeira linha de A
print("Primeira e terceira linha de A:")
print(A[[0,2]], "dimensão:", A[[0,2]].shape) # Primeira e terceira linha de A
print("Primeira linha de A (mantendo 2 dimensões):")
print(A[[0]], "dimensão:", A[[0]].shape) # Primeira linha de A (mantendo 2 dimensões)

Primeira linha de A:
[2 0] dimensão: (2,)
Primeira e terceira linha de A:
[[2 0]
 [8 2]] dimensão: (2, 2)
Primeira linha de A (mantendo 2 dimensões):
[[2 0]] dimensão: (1, 2)


$$\begin{aligned}
\boldsymbol{A}[:,0] &= \begin{bmatrix}2 & 4 & 8\end{bmatrix}\\
\boldsymbol{A}[:,[0]] &= \begin{bmatrix}2 \\ 4 \\ 8\end{bmatrix}
\end{aligned}$$

In [ ]:
print("Primeira coluna do A:")
print(A[:,0], "dimensão:", A[:,0].shape) # Primeira coluna do A
print("Primeira e segunda coluna do A:")
print(A[:,[0,1]], "dimensão:", A[:,[0,1]].shape) # Primeira e segunda coluna do A
print("Primeira coluna do A (mantendo 2 dimensões):")
print(A[:,[0]], "dimensão:", A[:,[0]].shape) # Primeira coluna do A (mantendo 2 dimensões)

Primeira coluna do A:
[2 4 8] dimensão: (3,)
Primeira e segunda coluna do A:
[[2 0]
 [4 6]
 [8 2]] dimensão: (3, 2)
Primeira coluna do A (mantendo 2 dimensões):
[[2]
 [4]
 [8]] dimensão: (3, 1)


$$\begin{aligned}
\left[\begin{bmatrix}2 & 4 & 8\end{bmatrix}; \begin{bmatrix}1 & 2 & 3\end{bmatrix}\right] &= \begin{bmatrix}2 & 4 & 8\\1 & 2 & 3\end{bmatrix}\\
\left[\begin{bmatrix}2 \\ 4 \\ 8\end{bmatrix}, \begin{bmatrix}1 \\ 2 \\ 3\end{bmatrix}\right] &= \begin{bmatrix}2 & 1 \\ 4 & 2 \\ 8 & 3\end{bmatrix}
\end{aligned}$$

In [ ]:
a = np.array([2, 4, 8]).reshape((1,-1))
b = np.array([1, 2, 3]).reshape((1,-1))
ab = np.r_[a,b]

print(a, "dimensão:", a.shape)
print(b, "dimensão:", b.shape)
print(ab, "dimensão:", ab.shape) # row stack

[[2 4 8]] dimensão: (1, 3)
[[1 2 3]] dimensão: (1, 3)
[[2 4 8]
 [1 2 3]] dimensão: (2, 3)


In [ ]:
c = np.array([2, 4, 8]).reshape((-1,1))
d = np.array([1, 2, 3]).reshape((-1,1))
cd = np.c_[c,d]

print(c, "dimensão:", c.shape)
print(d, "dimensão:", d.shape)
print(cd, "dimensão:", cd.shape) # column stack

[[2]
 [4]
 [8]] dimensão: (3, 1)
[[1]
 [2]
 [3]] dimensão: (3, 1)
[[2 1]
 [4 2]
 [8 3]] dimensão: (3, 2)


## Matrizes notáveis

$$\begin{aligned}
\boldsymbol{I}_n = \mathtt{np.eye(n)} &= \begin{bmatrix}1 & 0 & \ldots\\ 0 & 1 & \ldots\\ \vdots&\vdots&\vdots\\ 0 & \ldots & 1\end{bmatrix}&
\boldsymbol{0}_{n,m} = \mathtt{np.zeros((n,m))} &= \begin{bmatrix}0 & 0 & \ldots\\ 0 & 0 & \ldots\\ \vdots&\vdots&\vdots\\ 0 & \ldots & 0\end{bmatrix}\\
\boldsymbol{1}_{n,m} = \mathtt{np.ones((n,m))} &= \begin{bmatrix}1 & 1 & \ldots\\ 1 & 1 & \ldots\\ \vdots&\vdots&\vdots\\ 1 & \ldots & 1\end{bmatrix}\\
\end{aligned}$$

In [ ]:
print("Matriz identidade de ordem 5:")
print(np.eye(6))
print("Matriz de zeros 5x3:")
print(np.zeros((5,3)))
print("Matriz de uns 3x1:")
print(np.ones((3,1)))

Matriz identidade de ordem 5:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Matriz de zeros 5x3:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriz de uns 3x1:
[[1.]
 [1.]
 [1.]]


Além dessas matrizes notáveis, também podemos fazer matrizes aleatórias:

`np.random.rand(n,m)` é uma matrix $n$ por $m$ onde $[\mathtt{np.random.rand(n,m)}]_{ij} \sim \mathcal{U}(0,1)$.

Ou seja, $[\mathtt{np.random.rand(n,m)}]_{ij} \in [0,1)$

`np.random.randn(n,m)` é uma matrix $n$ por $m$ onde $[\mathtt{np.random.randn(n,m)}]_{ij} \sim \mathcal{N}(0,1)$

Ou seja, $[\mathtt{np.random.randn(n,m)}]_{ij} \in (-\infty,+\infty)$

In [ ]:
print("Matriz 5x3 de números aleatórios amostrados de U(0,1):")
print(np.random.rand(5,3))
print("Matriz 2x2 de números aleatórios amostrados de N(0,1):")
print(np.random.randn(2,2))

Matriz 5x3 de números aleatórios amostrados de U(0,1):
[[0.86256196 0.53925865 0.70451595]
 [0.40289098 0.91853528 0.94351002]
 [0.77808543 0.2656899  0.17151975]
 [0.04516685 0.40147992 0.70187851]
 [0.4540788  0.84873333 0.18550957]]
Matriz 2x2 de números aleatórios amostrados de N(0,1):
[[-0.47307795  1.77036489]
 [-0.48829459 -1.13229198]]


## Operações lineares

Produto de escalares por matrizes:
$$\begin{aligned}
5\boldsymbol{A} &= \begin{bmatrix}2\cdot 5 & 0\cdot 5\\ 4\cdot 5 & 6\cdot 5\\ 8\cdot 5 & 2\cdot 5\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}10 & 0\\ 20 & 30\\ 40 & 10\end{bmatrix}
\end{aligned}$$

In [ ]:
print(5 * A)

[[10  0]
 [20 30]
 [40 10]]


Soma de matrizes:
$$\begin{aligned}
\boldsymbol{A}+\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}+\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}4 & 0\\ 8 & 12\\ 26 & 4\end{bmatrix}
\end{aligned}$$

In [ ]:
print(A + A)

[[ 4  0]
 [ 8 12]
 [16  4]]


Produto com broadcast (difusão) de um vetor por uma matriz:
$$\begin{aligned}
\boldsymbol{v}_1 \bullet \boldsymbol{A} &= \begin{bmatrix}5 & 3\end{bmatrix}\bullet\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}5\cdot 2 & 3\cdot 0\\ 5\cdot 4 & 3\cdot 6\\ 5\cdot 8 & 3\cdot 2\end{bmatrix}\\
&= \begin{bmatrix}10 & 0\\ 20 & 18\\ 40 & 6\end{bmatrix}\\
\end{aligned}$$

In [ ]:
print(v1 * A)

[[10  0]
 [20 18]
 [40  6]]


Soma com broadcast (difusão) de um vetor por uma matriz:
$$\begin{aligned}
\boldsymbol{v}_1 \oplus \boldsymbol{A} &= \begin{bmatrix}5 & 3\end{bmatrix}\oplus\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}5 & 3\\ 5 & 3\\ 5 & 3\end{bmatrix}+\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
&= \begin{bmatrix}7 & 3\\ 9 & 9\\ 13 & 5\end{bmatrix}\\
\end{aligned}$$

In [ ]:
print(v1 + A)

[[ 7  3]
 [ 9  9]
 [13  5]]


Cuidado com as dimensões das variáveis:

In [ ]:
print("Vetor v2:")
print(v2, "dimensão:", v2.shape)
print("Matriz A:")
print(A, "dimensão:", A.shape)
try:
    v2 + A
except Exception as e:
    print(e)

Vetor v2:
[9 2 1] dimensão: (3,)
Matriz A:
[[2 0]
 [4 6]
 [8 2]] dimensão: (3, 2)
operands could not be broadcast together with shapes (3,) (3,2) 


In [ ]:
print("Matriz A:")
print(A, "dimensão:", A.shape)
print("Matriz B:")
print(B, "dimensão:", B.shape)
try:
    A + B
except Exception as e:
    print(e)

Matriz A:
[[2 0]
 [4 6]
 [8 2]] dimensão: (3, 2)
Matriz B:
[[1 3]
 [5 7]] dimensão: (2, 2)
operands could not be broadcast together with shapes (3,2) (2,2) 


## Operações não-lineares

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{A ** 2} &= \begin{bmatrix}2^2 & 0^2\\ 4^2 & 6^2\\ 8^2 & 2^2\end{bmatrix}
\end{aligned}$$

In [ ]:
print(A ** 2)

[[ 4  0]
 [16 36]
 [64  4]]


$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.sqrt(A)} &= \begin{bmatrix}\sqrt{2} & \sqrt{0}\\ \sqrt{4} & \sqrt{6}\\ \sqrt{8} & \sqrt{2}\end{bmatrix}\\
\mathtt{A ** 0.5} &= \begin{bmatrix}2^\frac{1}{2} & 0^\frac{1}{2}\\ 4^\frac{1}{2} & 6^\frac{1}{2}\\ 8^\frac{1}{2} & 2^\frac{1}{2}\end{bmatrix}
\end{aligned}$$

In [ ]:
print(np.sqrt(A))
print(A ** 0.5)

[[1.41421356 0.        ]
 [2.         2.44948974]
 [2.82842712 1.41421356]]
[[1.41421356 0.        ]
 [2.         2.44948974]
 [2.82842712 1.41421356]]


## Operações de agregação

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A)} &= \frac{2 + 0 + 4 + 6 + 8 + 2}{2\cdot 3}\\
\mathtt{np.sum(A)} &= 2 + 0 + 4 + 6 + 8 + 2\\
\mathtt{np.prod(A)} &= 2 \cdot 0 \cdot 4 \cdot 6 \cdot 8 \cdot 2\\
\end{aligned}$$

In [ ]:
np.mean(A), np.sum(A), np.prod(A)

(3.6666666666666665, 22, 0)

In [ ]:
A.mean(), A.sum(), A.prod()

(3.6666666666666665, 22, 0)

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A, axis=0)} &= \frac{1}{3}\begin{bmatrix}2 + 4 + 8 & 0 + 6 + 2\end{bmatrix}\\
\mathtt{np.sum(A, axis=0)} &= \begin{bmatrix}2 + 4 + 8 & 0 + 6 + 2\end{bmatrix}\\
\mathtt{np.prod(A, axis=0)} &= \begin{bmatrix}2 \cdot 4 \cdot 8 & 0 \cdot 6 \cdot 2\end{bmatrix}\\
\end{aligned}$$

In [ ]:
np.mean(A, axis=0), np.sum(A, axis=0), np.prod(A, axis=0)

(array([4.66666667, 2.66666667]), array([14,  8]), array([64,  0]))

In [ ]:
A.mean(axis=0), A.sum(axis=0), A.prod(axis=0)

(array([4.66666667, 2.66666667]), array([14,  8]), array([64,  0]))

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A, axis=1)} &= \frac{1}{2}\begin{bmatrix}2 + 0 & 4 + 6 & 8 + 2\end{bmatrix}\\
\mathtt{np.sum(A, axis=1)} &= \begin{bmatrix}2 + 0 & 4 + 6 & 8 + 2\end{bmatrix}\\
\mathtt{np.prod(A, axis=1)} &= \begin{bmatrix}2 \cdot 0 & 4 \cdot 6 & 8 \cdot 2\end{bmatrix}\\
\end{aligned}$$

In [ ]:
np.mean(A, axis=1), np.sum(A, axis=1), np.prod(A, axis=1)

(array([1., 5., 5.]), array([ 2, 10, 10]), array([ 0, 24, 16]))

In [ ]:
A.mean(axis=1), A.sum(axis=1), A.prod(axis=1)

(array([1., 5., 5.]), array([ 2, 10, 10]), array([ 0, 24, 16]))

In [ ]:
np.mean(A, axis=0, keepdims=True)

array([[4.66666667, 2.66666667]])

In [ ]:
A.mean(axis=0, keepdims=True)

array([[4.66666667, 2.66666667]])

In [ ]:
A - A.mean(axis=0, keepdims=True)

array([[-2.66666667, -2.66666667],
       [-0.66666667,  3.33333333],
       [ 3.33333333, -0.66666667]])

## Multiplicação de Matrizes

Para matrizes $\boldsymbol{X} \in \mathbb{R}^{a\times b}$ e $\boldsymbol{Y} \in \mathbb{R}^{b\times c}$, temos que
$\boldsymbol{XY} \in \mathbb{R}^{a\times c}$. No Numpy, essa operação é representada por $\texttt{X @ Y}$.

A multiplicação é definida por:
$$\begin{aligned}
(\boldsymbol{XY})_{ij} = \sum_k \boldsymbol{X}_{ik}\boldsymbol{Y}_{kj}
\end{aligned}$$

In [ ]:
print(A @ B)
print("Dimensão de A @ B:", (A@B).shape)

[[ 2  6]
 [34 54]
 [18 38]]
Dimensão de A @ B: (3, 2)


In [ ]:
A

array([[2, 0],
       [4, 6],
       [8, 2]])

In [ ]:
B

array([[1, 3],
       [5, 7]])

Cuidado com as dimensões das matrizes:

In [ ]:
try:
    B @ A
except Exception as e:
    print(e)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [ ]:
print(A @ B @ v1)
print((A @ B) @ v1)

[ 28 332 204]
[ 28 332 204]


### Inversão de matrizes
Outra operação bastante comum é multiplicar uma matriz pela inversa dela...

Seja $\boldsymbol{B}$ uma matriz inversível, então $\boldsymbol{B}^{-1} \boldsymbol{B} = \boldsymbol{I}$


In [ ]:
print(B)

[[1 3]
 [5 7]]


In [ ]:
B_inv = np.linalg.inv(B)
print(B_inv)

[[-0.875  0.375]
 [ 0.625 -0.125]]


In [ ]:
print(B_inv @ B)

[[1. 0.]
 [0. 1.]]


A inversa pode ser usada no produto com vetores:
$\boldsymbol{B}^{-1} \boldsymbol{v}_1$

In [ ]:
print(B_inv @ v1)

[-3.25  2.75]


Porém, existe uma outra forma mais eficiente de computar a mesma coisa:

Se $\boldsymbol{B}^{-1} \boldsymbol{v}_1 = \boldsymbol{x}$, então $\boldsymbol{B} \boldsymbol{x} = \boldsymbol{v}_1$.
Ou seja, estamos resolvendo o sistema de equações lineares com coeficientes $\boldsymbol{B}$ e resultado $\boldsymbol{v}_1$

In [ ]:
print(np.linalg.solve(B,v1))

[-3.25  2.75]


## Leitura de arquivos com dados

Normalmente os dados na disciplina serão recebidos no formato CSV. Isso significa que o dado é estruturado da seguinte maneira:
```
idade,pressão_sanguínea # Um cabeçalho opcional
39,144 # Dados separados por vírgulas ou outro separador
47,220
....
```

In [ ]:
pressao = np.genfromtxt(r'/content/drive/MyDrive/UFC_mestrado/Sigaa_UFC/1_semestre/aprendizagem_automatica/NotebookTutorialNumpy/pressao.txt', delimiter=',', skip_header=1)
pressao

array([[ 39., 144.],
       [ 47., 220.],
       [ 45., 138.],
       [ 47., 145.],
       [ 65., 162.],
       [ 46., 142.],
       [ 67., 170.],
       [ 42., 124.],
       [ 67., 158.],
       [ 56., 154.],
       [ 64., 162.],
       [ 56., 150.],
       [ 59., 140.],
       [ 34., 110.],
       [ 42., 128.],
       [ 48., 130.],
       [ 45., 135.],
       [ 17., 114.],
       [ 20., 116.],
       [ 19., 124.],
       [ 36., 136.],
       [ 50., 142.],
       [ 39., 120.],
       [ 21., 120.],
       [ 44., 160.],
       [ 53., 158.],
       [ 63., 144.],
       [ 29., 130.],
       [ 25., 125.],
       [ 69., 175.]])

```
# idade, temperatura da água, comprimento
14,25,620
28,25,1315
....
```

In [ ]:
peixe = np.genfromtxt(r'/content/drive/MyDrive/UFC_mestrado/Sigaa_UFC/1_semestre/aprendizagem_automatica/NotebookTutorialNumpy/peixe.txt', delimiter=',')
peixe

array([[  14.,   25.,  620.],
       [  28.,   25., 1315.],
       [  41.,   25., 2120.],
       [  55.,   25., 2600.],
       [  69.,   25., 3110.],
       [  83.,   25., 3535.],
       [  97.,   25., 3935.],
       [ 111.,   25., 4465.],
       [ 125.,   25., 4530.],
       [ 139.,   25., 4570.],
       [ 153.,   25., 4600.],
       [  14.,   27.,  625.],
       [  28.,   27., 1215.],
       [  41.,   27., 2110.],
       [  55.,   27., 2805.],
       [  69.,   27., 3255.],
       [  83.,   27., 4015.],
       [  97.,   27., 4315.],
       [ 111.,   27., 4495.],
       [ 125.,   27., 4535.],
       [ 139.,   27., 4600.],
       [ 153.,   27., 4600.],
       [  14.,   29.,  590.],
       [  28.,   29., 1305.],
       [  41.,   29., 2140.],
       [  55.,   29., 2890.],
       [  69.,   29., 3920.],
       [  83.,   29., 3920.],
       [  97.,   29., 4515.],
       [ 111.,   29., 4520.],
       [ 125.,   29., 4525.],
       [ 139.,   29., 4565.],
       [ 153.,   29., 4566.],
       [  

## Exercícios

### Computar a fórmula da normalização escore-Z

Dado um conjunto de dados $\boldsymbol{X} = [\boldsymbol{x}_1, \boldsymbol{x}_1, \ldots, \boldsymbol{x}_N]$, a normalização por escore-Z é dada por:
$$\tilde{\boldsymbol{x_i}} = \frac{\boldsymbol{x_i} - \boldsymbol{\mu}}{\boldsymbol{\sigma}}$$

Onde:
$$\begin{aligned}
\boldsymbol{\mu} &= \frac{1}{N}\sum_i^N \boldsymbol{x_i}\\
\boldsymbol{\sigma} &= \sqrt{\frac{1}{N-1}\sum_i^N (\boldsymbol{x_i}-\boldsymbol{\mu})^2}\\
\end{aligned}$$

A "desnormalização" pode ser feita por:
$$\boldsymbol{x_i} = \boldsymbol{\sigma}\tilde{\boldsymbol{x_i}} + \boldsymbol{\mu}$$

Use a fórmula para normalizar o conjunto de dados `peixe` sem usar nenhum `for` ou `while`.

In [ ]:
# Escreva o código aqui

normalizacao = peixe
media = normalizacao.mean()
desvio_padrao = normalizacao.std()

escore_z = (normalizacao-media)/desvio_padrao
escore_z
dados = escore_z
escore_z

array([[-0.65092535, -0.64416326, -0.27839585],
       [-0.64231906, -0.64416326,  0.14884508],
       [-0.6343275 , -0.64416326,  0.64370687],
       [-0.62572121, -0.64416326,  0.93877974],
       [-0.61711492, -0.64416326,  1.25229466],
       [-0.60850862, -0.64416326,  1.5135571 ],
       [-0.59990233, -0.64416326,  1.75945116],
       [-0.59129604, -0.64416326,  2.08526079],
       [-0.58268975, -0.64416326,  2.12521857],
       [-0.57408346, -0.64416326,  2.14980798],
       [-0.56547716, -0.64416326,  2.16825003],
       [-0.65092535, -0.64293379, -0.27532218],
       [-0.64231906, -0.64293379,  0.08737156],
       [-0.6343275 , -0.64293379,  0.63755952],
       [-0.62572121, -0.64293379,  1.06480044],
       [-0.61711492, -0.64293379,  1.34143126],
       [-0.60850862, -0.64293379,  1.80862997],
       [-0.59990233, -0.64293379,  1.99305052],
       [-0.59129604, -0.64293379,  2.10370284],
       [-0.58268975, -0.64293379,  2.12829225],
       [-0.57408346, -0.64293379,  2.168

In [ ]:
# coeficiente linear

# calculando a 'coeficiente linear'

a = dados[1].mean() - ( b * dados[0].mean())
a

In [ ]:
dados[:,:-1]

### Encontrar raízes de funções

Dada uma função $f$, o seguinte procedimento (método de Newton-Raphson) consegue encontrar aproximar zeros desta função:

1. Inicialize $\tilde{x}_0$ com um chute inicial e escolha uma tolerância $\epsilon$;
2. Compute: $$\tilde{x}_{t} = \tilde{x}_{t-1} - \frac{f(\tilde{x}_{t-1})}{f'(\tilde{x}_{t-1})}$$
3. Repita o passo 2 até que $f(\tilde{x}_t) \leq \epsilon$.

Implemente esse procedimento para $f(x) = x^2 - 2$, teste seu resultado computando $\tilde{x} \cdot \tilde{x}$.

![imagem](https://www.researchgate.net/publication/332069106/figure/fig1/AS:741590217789442@1553820294415/Figura-4-Demonstracao-visual-do-metodo-de-Newton-Raphson-2-iteracoes.ppm)

In [ ]:

x = pressao

funcao_de_x = (x**2) - 2
derivada_da_funcao = 2 * x


x_n = x - (funcao_de_x / derivada_da_funcao)


In [ ]:
np.min(x_n)

8.558823529411764

In [ ]:
# Escreva o código aqui

def f(x):
    return x**2 - 2

def f_derivada(x):
    return 2 * x

def metodo_newton_raphson(chute_inicial, tolerancia):
    x_atual = chute_inicial
    while True:
        f_atual = f(x_atual)
        if abs(f_atual) <= tolerancia:
            break
        x_proximo = x_atual - f_atual / f_derivada(x_atual)
        x_atual = x_proximo
    return x_atual

# Defina um chute inicial e uma tolerância
chute_inicial = 1.5
tolerancia = 1e-6

# Encontre a raiz usando o método de Newton-Raphson
raiz = metodo_newton_raphson(chute_inicial, tolerancia)

# Calcule f(x~) * x~
resultado = f(raiz) * raiz

print("Raiz encontrada:", raiz)
print("Resultado de f(x~) * x~:", resultado)


Raiz encontrada: 1.4142135623746899
Resultado de f(x~) * x~: 6.378971641147635e-12


In [ ]:
# Definindo dois vetores
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Produto interno usando o operador @
dot_product = v1 @ v2
dot_product

# Regressão linear via mínimos quadrados ordinários (OLS)

Como visto na aula de regressão linear, dado o seguinte problema:
$$\begin{aligned}
\hat{\boldsymbol{y}} = \boldsymbol{X}\boldsymbol{w}\\
\text{Queremos encontrar:}\\
\hat{\boldsymbol{w}} = \arg\min_{\boldsymbol{w}} ||\boldsymbol{y} - \boldsymbol{X}\boldsymbol{w}||^2
\end{aligned}$$

Como visto, sabemos que:
$$\hat{\boldsymbol{w}} = (\boldsymbol{X}^{\top}\boldsymbol{X})^{-1} \boldsymbol{X}^{\top}\boldsymbol{y}$$

Obtenha um modelo linear para predizer o comprimento de um peixe a partir de sua idade e da temperatura da água. Para isso, encontre o $\hat{\boldsymbol{w}}$ pro dataset `peixe` onde:
$$\boldsymbol{X} = [\mathbf{1}^{\top} \;,\; \mathtt{peixe\underline{}dataset[:,[0,1]}]\\
\boldsymbol{y} = \mathtt{peixe\underline{}dataset[:,[2]]}$$

Sem utilizar estrutura de repetição alguma, calcule a raíz do erro quadrático médio:
$$\mathrm{RMSE} = \sqrt{\frac{1}{n}\sum_i^n (\boldsymbol{y} - \hat{\boldsymbol{y}})^2}$$

In [ ]:
x = peixe[:,0:2]
x

In [ ]:
y = peixe[:,-1]

In [ ]:
multiplicacao_de_matriz = x.T @ x
multiplicacao_de_matriz

inverso_da_matriz = np.linalg.inv(multiplicacao_de_matriz)

array([[389684., 102480.],
       [102480.,  34716.]])

In [ ]:
inverso_da_matriz = np.linalg.inv(multiplicacao_de_matriz)
inverso_da_matriz

array([[ 1.14721186e-05, -3.38651548e-05],
       [-3.38651548e-05,  1.28773507e-04]])

In [ ]:
inverso_da_matriz @ x.T @ y

array([27.27954198, 29.07413117])

In [ ]:
def teta(x,y):
  matriz_x_transpor = x.T
  matriz_x = x
  produto_matriz = matriz_x_transpor @ matriz_x
  inverso_da_matriz = np.linalg.inv(produto_matriz)
  teta_w1_w0 = inverso_da_matriz @ matriz_x_transpor @ y
  return teta_w1_w0

In [ ]:
teta(x,y)

array([27.27954198, 29.07413117])

In [ ]:
# Agora você pode calcular a inversa de X^T X
# XTX_inv = np.linalg.inv(np.dot(X.T, X))

# # E continuar com a equação para encontrar os coeficientes
# w = np.dot(np.dot(XTX_inv, X.T), y)

# Regressão linear via gradiente descendente (GD)

Sendo $\alpha$ um passo de aprendizagem, $N$ o número de observações disponíveis e $t$ a iteração atual do algoritmo, os parâmetros $\boldsymbol{w}$ podem ser atualizados via algoritmo GD:

$$\boldsymbol{w}(t) = \boldsymbol{w}(t-1) + \alpha \frac{1}{N}\sum_{i=1}^{N} e_i(t-1) \boldsymbol{x}_i,$$
$$\text{em que } e_i(t-1) = y_i - \boldsymbol{w}^{\top}(t-1)\boldsymbol{x}_i$$

Normalize os dados retirando a média e dividindo pelo desvio padrão (entrada e saída). Na predição, desfaça a normalização para computar o RMSE.

In [ ]:
# import numpy as np

# def gradient_descent_update(w_prev, x, y, learning_rate):
#     # Calculando o número total de observações
#     N = len(y)

#     # Calculando os erros residuais para todas as observações
#     residuals = y - np.dot(x, w_prev)

#     # Calculando a média ponderada dos vetores de características
#     weighted_sum = np.dot(x.T, residuals)

#     # Atualizando os parâmetros w(t)
#     w_new = w_prev + (learning_rate / N) * weighted_sum

#     return w_new


In [ ]:
# Escreva o código aqui
def gradiente_descendente(matriz_de_coeficientes, x, y, taxa_de_aprendizado = 0.01):
  # Calculando o número total de observações
  n = len(x)

  # calculando os erros residuais para todas as observações
  erro_residual = y - (x @ matriz_de_coeficientes)

  # Calculando a Média ponderada dos vetores de características
  media_ponderada_vetores = x.T @ erro_residual

  # Atualizando os parâmetros w(t)
  w_atualizado = matriz_de_coeficientes + (taxa_de_aprendizado / n) * media_ponderada_vetores

  return w_atualizado

In [ ]:
gradiente_descendente(teta(x,y), x, y)

array([27.27954198, 29.07413117])

# Regressão linear via gradiente descendente estocástico (SGD)

Sendo $\alpha$ um passo de aprendizagem, $N$ o número de observações disponíveis e $t$ a iteração atual do algoritmo, os parâmetros $\boldsymbol{w}$ podem ser atualizados via algoritmo SGD:

$$\boldsymbol{w}(t) = \boldsymbol{w}(t-1) + \alpha e_i(t-1) \boldsymbol{x}_i,$$
$$\text{em que } e_i(t-1) = y_i - \boldsymbol{w}^{\top}(t-1)\boldsymbol{x}_i$$

Normalize os dados retirando a média e dividindo pelo desvio padrão (entrada e saída). Na predição, desfaça a normalização para computar o RMSE.

In [ ]:
import numpy as np

def stochastic_gradient_descent_update(w_prev, x_i, y_i, learning_rate=0.01):
    # Adiciona uma dimensão extra a x_i para torná-lo bidimensional (1 x n)
    x_i = np.expand_dims(x_i, axis=0)

    # Adiciona uma dimensão extra a y_i para torná-lo bidimensional (1 x 1)
    y_i = np.expand_dims(y_i, axis=0)

    # Calcula a previsão para o exemplo atual
    y_pred = np.dot(x_i, w_prev)

    # Calcula o erro residual para o exemplo atual
    residual = y_i - y_pred

    # Atualiza os parâmetros w(t) usando o gradiente para o exemplo atual
    w_new = w_prev + learning_rate * np.dot(x_i.T, residual)

    return w_new



In [ ]:

stochastic_gradient_descent_update(teta(x,y), x, y)




ValueError: operands could not be broadcast together with shapes (2,) (2,44,44) 

In [ ]:
# from sklearn.linear_model import LinearRegression
# import numpy as np

# def teta(x,y):
#   """
#   Calcula os parâmetros do modelo de regressão linear utilizando a equação normal.

#   Parâmetros:
#   - x: matriz de características (incluindo um termo de bias, se necessário)
#   - y: vetor de saída

#   Retorna:
#   - theta: vetor de parâmetros do modelo
#   """

#   # Adicionar um termo de bias (coluna de 1s) à matriz de características
#   x_com_bias = np.hstack((np.ones((x.shape[0], 1)), x))

#   # Calcular os parâmetros do modelo de regressão linear
#   matriz_x_transposta = x_com_bias.T
#   produto_matriz = matriz_x_transposta @ x_com_bias
#   inverso_da_matriz = np.linalg.inv(produto_matriz)
#   theta = inverso_da_matriz @ matriz_x_transposta @ y
#   return theta

# # Exemplo de uso:
# # Suponha que 'x' seja a matriz de características e 'y' seja o vetor de saída
# # 'x' deve ter a forma (número_de_amostras, número_de_características)
# # 'y' deve ter a forma (número_de_amostras,)

# # Gerar dados de exemplo

# # Calcular os parâmetros do modelo usando a função teta
# theta_funcao = teta(x_treino[:,0].reshape(-1, 1), y_treino)

# # Treinar um modelo de regressão linear usando scikit-learn
# modelo = LinearRegression()  # Desabilita o ajuste do intercepto, pois já temos o termo de bias em 'x'
# modelo.fit(x_treino[:,0].reshape(-1, 1), y_treino)
# theta_sklearn = modelo.coef_

# # Comparar os resultados
# print("Parâmetros do Modelo (Função):", theta_funcao)
# print("Parâmetros do Modelo (scikit-learn):", theta_sklearn)
# print("Coeficiente Linear (scikit-learn):", modelo.intercept_)

In [ ]:
# from sklearn.preprocessing import PolynomialFeatures

# # Suponha que 'x_treinamento' seja a matriz de características do conjunto de treinamento

# # Criar objeto PolynomialFeatures com o grau desejado
# grau = 3  # Definindo o grau do polinômio
# poly = PolynomialFeatures(grau)

# # Transformar as características para incluir características polinomiais
# x_treinamento_transformado = poly.fit_transform(x_treino[:,0].reshape(-1,1))

# # Exibir as dimensões dos dados transformados
# print("Dimensões dos dados transformados:", x_treinamento_transformado.shape)
# print("Dimensões dos dados transformados:", x_treinamento_transformado[:3])

# # Treinar um modelo de regressão linear usando scikit-learn
# modelo = LinearRegression()  # Desabilita o ajuste do intercepto, pois já temos o termo de bias em 'x'
# modelo.fit(x_treinamento_transformado, y_treino)
# theta_sklearn = modelo.coef_

# print("Parâmetros do Modelo (scikit-learn):", theta_sklearn)
# print("Coeficiente Linear (scikit-learn):", modelo.intercept_)

In [ ]:
# def coeficientes_minimos_quadrados(x,y):
#   # todos esses calculos abaixo tem como objetivo de calcular a derivada de w0 e w1.
#   # x e y são os arrays das variáveis independentes e dependentes, respectivamente
#   #criando variaveis
#   # Calculando o produto entre x e y
#   xy = x * y
#   # Calculando a soma dos quadrados de x
#   x2 = x**2
#   # Calculando a soma dos quadrados de y
#   y2 = y**2
#   # Obtendo o número de observações
#   n = len(x)
#   # Calculando o coeficiente angular (w1) usando a fórmula dos mínimos quadrados
#   w1 = ((n * xy.sum())  - (x.sum() * y.sum())) / (n * (x2.sum()) - (x.sum()**2))
#   # Calculando o coeficiente linear (w0)
#   w0 = y.mean() - ( w1 * x.mean())
  # return w1 ,w0